### ISSUE TITLE
Extract `test_code` values

### ISSUE THREAD

**Issue by cmcaine** [exercism/julia-test-runner#26]
Following a chat on slack, I said I'd have a look at this. Here's a summary of my understanding of the issue and a suggestion for how to solve it.

Observations:

1. We are asked to provide a simple failing test case as runnable code when tests fail
   - This is important because the runtests.jl file is not visible to students doing concept exercises
   - This is optional for practice exercises
   -  reference: https://github.com/exercism/docs/blob/main/building/tooling/test-runners/interface.md#test-code
2. For simple tests, the default message is probably good enough?

```
julia> f(x) = 5x
f (generic function with 1 method)

julia> @test f(2) == 3
Test Failed at REPL[37]:1
  Expression: f(2) == 3
   Evaluated: 10 == 3
ERROR: There was an error during testing
```

3. For tests with setup, we will want to capture that setup, e.g. by capturing the body of the testset by providing our own macro or through other metaprogramming
4. If we use helper functions or imports in testing, that could be tricky, too.
5. We're using lots of testsets so that we can give friendly descriptions to the tests
6. That's not how Test is expected to be used, so the output is a bit too verbose
7. We can reduce verbosity with nested tests

How about this:

1. We use metaprogramming to capture the descriptions and bodies of all the tests
2. When a test fails, we give the complete body of the testset it is immediately contained by
3. We never use features in a test that are not defined in Base, the exercise or its immediately containing testset
4. `tojson` is adjusted to support nested test sets
   - It either concatenates descriptions from nested testsets or takes only the inner most description
5. A metaprogramming solution also allows us to collect stdout/stderr from individual testsets rather than from only the outermost testset, which is a slight improvement

This allows us to retain nested test sets (the `tojson` function in the test runner will need to be updated, but that's no big deal, really.

Example test_code values:

```
using Test

@testset "description here" begin
    some_setup = 1
    @test f(some_setup) == 10
end
```

Or, possibly:

```
using Test

some_setup = 1
@test f(some_setup) == 10
```

Or

```
some_setup = 1
@assert f(some_setup) == 10
```

An implementation like this seems fine?

```julia
using Test

testset_bodies = Dict()

macro exercism_testset(args...)
    tests = last(args)
    f(ts) = testset_bodies[ts] = tests
    return quote
        local ts = Test.@testset $(args...)
        $f(ts)
        return ts
    end
end

@exercism_testset "desc" begin
    @test 1 == 1
end
```

Where you then match up the testset_bodies with the testsets returned by the ReportingTestSet.

`@testset` in the original files is replaced by some other metaprogramming or by just defining our own `@testset` first.

Capturing stdin/stdout also left as an exercise for the reader.

**Comment by cmcaine** [comment]
You're welcome :)

The dict is indexed by the testset object returned, so unique descriptions isn't a big deal there. That seems easier and less fragile to me than a vector?

Happy / agree to the rest

**Comment by SaschaMann** [comment]
> The dict is indexed by the testset object returned, so unique descriptions aren't a big deal there. That seems easier and less fragile to me than a vector?

I missed that part, sorry. Yea in that case I agree, let's use the dict.

I'll try to incorporate this into the test runner over the weekend.

**Comment by ErikSchierboom** [comment]
Just curious: any updates on this?
