### ISSUE TITLE
Report test_code for passing tests

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/julia-test-runner#37]
We've recently updated the [test runner interface specification](https://github.com/exercism/docs/blob/main/building/tooling/test-runners/interface.md) to allow for two types of test runners, identified via a new `version` property in the `results.json` file (see [the spec for the version property](https://github.com/exercism/docs/blob/main/building/tooling/test-runners/interface.md#version)):

1. `version: 1` test runners are quite basic, and only detect if either all tests passed or not. These test runners capture the console output of the test runner and output that. They do _not_ include details on individual tests passing/failing
2. `version: 2` test runners contain detailed information on individual tests passing/failing. We've recently added a required field named `test_code`, which contains the code the test ran to verify the behavior (see [the spec for the test_code property](https://github.com/exercism/docs/blob/main/building/tooling/test-runners/interface.md#test-code)).

The test runner's output is currently what I refer to as version 1.5: it contains the individual test information, but does not yet contain the `test_code` key. If possible, the test runner should be updated to also include the test code, in which case the `version` property should also be added with `2` as its value.

You are completely free on how you want to extract the test code, either via the AST or via finding the test code in the source code text via string manipulation. 

Let me know if there are any questions.

**Comment by cmcaine** [comment]
We only provide `test_code` if the test failed or errored and that seems to be good enough for the website. Can we close this or should we be providing test_code for passing tests as well? Currently we set version = 2 for the JSON.

**Comment by ErikSchierboom** [comment]
> We only provide test_code if the test failed or errored and that seems to be good enough for the website. 

That is indeed good enough. We _do_ support showing the test code for passing tests, but the purpose of the test code is to help with figuring out what went wrong for a failing test.

> Can we close this or should we be providing test_code for passing tests as well? 

Your choice basically. If, realistically, the feature could be implemented in the future, you could keep it open. You could also close this and open a new, more specific issue.

**Comment by cmcaine** [comment]
Thanks for clarifying! I'll leave this open and change the title.

**Comment by SaschaMann** [comment]
Is this not the case already?

![grafik](https://user-images.githubusercontent.com/20866761/172388930-78195f26-9ad0-4771-affe-9871008a9fd9.png)

**Comment by ErikSchierboom** [comment]
Apparently! This can be closed then.

**Comment by cmcaine** [comment]
Oh, lol, I forgot I had fixed this for passing tests too.
