### ISSUE TITLE
Include standard libraries in ExercismTestReports

### ISSUE THREAD

**Issue by SaschaMann** [exercism/julia-test-runner#52]
Currently running the test-runner on solutions that include packages like `Random` or `Dates` results in a warning:

```
[PRACTICE] Testing robot-name
┌ Warning: Package ExercismTestReports does not have Random in its dependencies:
│ - If you have ExercismTestReports checked out for development and have
│   added Random as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with ExercismTestReports
└ Loading Random into ExercismTestReports from project dependency, future warnings for ExercismTestReports are suppressed.
```

It might be nice to prevent this, since stdlib packages should be fine to use in the solution. I don't think this causes problems in practice, however.

**Comment by mizlan** [comment]
I'm running into this error while trying to submit a solution for the Robot Names problem.

@cmcaine I see this in the output, and I can't seem to resolve this by any means of submitting code.

<img width="678" alt="Screen Shot 2022-09-06 at 2 31 49 PM" src="https://user-images.githubusercontent.com/44309097/188744617-02e57f57-5216-4fdc-b8a8-f062eb4b2267.png">

**Comment by wilsongoode** [comment]
Experiencing this issue on the Gigasecond exercise as well.
![Screen Shot 2022-09-16 at 4 19 52 PM](https://user-images.githubusercontent.com/45737196/190726280-adf10edc-e7e7-42fe-bcab-8e30f83f594d.png)

**Comment by cmcaine** [comment]
This should probably be easy to fix. I think maybe Julia has got stricter
about standard libraries being available if you haven't listed them as
dependencies.

I'll try to remember to work on this this week, but the PR should be simple:

1. Make a test case which fails with LoadError when it tries to load some
common standard libraries.
2. Add the most commonly used (or all?) standard libraries as dependents of
ExercismTestReports
3. Check the tests pass and push for review.

Please feel free to take on this work.

**Comment by rfritz** [comment]
The clock exercise also shows this error, before, even, any code is written.

**Comment by KevinArlin** [comment]
This isn't done. For example, the ReverseString problem uses the Unicode library.

**Comment by SaschaMann** [comment]
Thanks for pointing that out
