### ISSUE TITLE
Counting characters in Julia 1.6

### ISSUE THREAD

**Issue by leoflotor** [exercism/julia-test-runner#67]
Hi!

The nucleotide count problem has an issue which I believe it to be related to the version of Julia 1.6.3 that is currently used while running the tests online.

My solution passes all the tests locally using Julia v1.7.1 but not online. This is my solution:
```
function count_nucleotides(strand)
    nucleotides = ('A', 'C', 'G', 'T')
    count(unique(strand) .∉ Ref(nucleotides)) != 0 ? 
    throw(DomainError(nothing)) : 
    Dict([nucleotide => count(nucleotide, strand) for nucleotide in nucleotides])
end
```

The error message that shows up online is:
```
MethodError: objects of type Char are not callable
Stacktrace:
  [1] _simple_count
    @ ./reduce.jl:970 [inlined]
  [2] #count#233
    @ ./reduce.jl:965 [inlined]
  [3] count
    @ ./reduce.jl:965 [inlined]
  [4] #9
    @ ./none:0 [inlined]
  [5] iterate
    @ ./generator.jl:47 [inlined]
  [6] collect(itr::Base.Generator{NTuple{4, Char}, ExercismTestReports.var"#9#10"{String}})
    @ Base ./array.jl:681
  [7] count_nucleotides(strand::String)
    @ ExercismTestReports ./nucleotide-count.jl:11
  [8] macro expansion
    @ ./runtests.jl:10 [inlined]
  [9] macro expansion
    @ [...]/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [10] top-level scope
    @ ./runtests.jl:10
```

And this error message occurs on tests 2,3 and 4. Apparently there is an issue with `count` for `Char` types.

The [workaround](https://discourse.julialang.org/t/method-for-counting-characters-in-string-count-a-batman-vs-count-a-batman/51153) is something like:

```
function count_nucleotides(strand)
    nucleotides = ('A', 'C', 'G', 'T')
    count(unique(strand) .∉ Ref(nucleotides)) != 0 ? 
    throw(DomainError(nothing)) : 
    Dict([nucleotide => count(==(nucleotide), strand) for (nucleotide) in nucleotides])
end
```

I know it is a small change, nevertheless it is a difference between Julia versions.

**Comment by SaschaMann** [comment]
Thanks for reporting this issue!

I've opened #68 to update the test runner to Julia 1.7.2, which should hopefully fix this issues :) Sorry for the inconvenience, I forgot to update this for quite a while!
